module TwistyPuzzles
  # Base class for directions.
  class AbstractDirection
    include Comparable

    POSSIBLE_DIRECTION_NAMES: ::Array[::Array[::String]]

    SIMPLE_DIRECTION_NAMES: ::Array[::String]

    POSSIBLE_SKEWB_DIRECTION_NAMES: ::Array[::Array[::String]]

    SIMPLE_SKEWB_DIRECTION_NAMES: ::Array[::String]

    @value: ::Integer

    def initialize: (::Integer value) -> untyped

    attr_reader value: ::Integer

    def <=>: (self other) -> ::Integer

    def zero?: () -> bool

    def non_zero?: () -> bool

    def inverse: () -> self

    def +: (self other) -> self

    def eql?: (untyped other) -> bool

    alias == eql?

    def hash: () -> ::Integer
  end
end
