module TwistyPuzzles
  # Intermediate base class for all types of moves that have an axis face and a direction,
  # i.e. cube moves and rotations.
  class AxisFaceAndDirectionMove < AbstractMove
    def initialize: (Face axis_face, untyped direction) -> untyped

    attr_reader direction: untyped

    attr_reader axis_face: untyped

    def translated_direction: (Face other_axis_face) -> untyped

    def same_axis?: (AxisFaceAndDirectionMove other) -> untyped

    def identifying_fields: () -> ::Array[untyped]

    def canonical_direction: () -> untyped

    def can_swap?: (untyped other) -> untyped

    def swap_internal: (untyped other) -> untyped

    def rotate_by: (untyped rotation) -> untyped

    def mirror: (untyped normal_face) -> untyped
  end
end
