module TwistyPuzzles
  # Represents the direction of a cube move or rotation.
  class CubeDirection < AbstractDirection
    NUM_DIRECTIONS: ::Integer

    NON_ZERO_DIRECTIONS: ::Array[CubeDirection]

    ALL_DIRECTIONS: ::Array[CubeDirection]

    ZERO: CubeDirection

    FORWARD: CubeDirection

    DOUBLE: CubeDirection

    BACKWARD: CubeDirection

    def name: () -> ::String

    def double_move?: () -> (::TrueClass | ::FalseClass)
  end
end
