module TwistyPuzzles
  # Factory for sticker cycles given part cycles.
  class PartCycleFactory
    include Utils::ArrayHelper

    def initialize: (::Integer cube_size, ::Integer incarnation_index) -> untyped

    def coordinates: (Part part) -> ::Array[Coordinate]

    def multi_twist: (::Array[Corner | Edge] parts) -> StickerCycles

    def check_type_consistency: (::Array[Part] parts) -> nil

    def construct: (::Array[Part] parts) -> StickerCycles
  end
end
