name: Rubocop

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Rubocop Linter Action
      uses: andrewmcodes/rubocop-linter-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
